#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PerilousMobile.Tests.Droid.Resource", IsApplication=true)]

namespace PerilousMobile.Tests.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Nunit.Runner.Resource.String.ApplicationName = global::PerilousMobile.Tests.Droid.Resource.String.ApplicationName;
			global::Nunit.Runner.Resource.String.Hello = global::PerilousMobile.Tests.Droid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::PerilousMobile.Tests.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::PerilousMobile.Tests.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0c0000
			public const int abc_action_bar_embed_tabs = 2131492864;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090003
			public const int notification_action_color_filter = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int notification_icon_bg_color = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int notification_material_background_media_default_color = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int primary_text_default_material_dark = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int ripple_material_light = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int secondary_text_default_material_dark = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int secondary_text_default_material_light = 2131296262;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0d0004
			public const int compat_button_inset_horizontal_material = 2131558404;
			
			// aapt resource value: 0x7f0d0005
			public const int compat_button_inset_vertical_material = 2131558405;
			
			// aapt resource value: 0x7f0d0006
			public const int compat_button_padding_horizontal_material = 2131558406;
			
			// aapt resource value: 0x7f0d0007
			public const int compat_button_padding_vertical_material = 2131558407;
			
			// aapt resource value: 0x7f0d0008
			public const int compat_control_corner_material = 2131558408;
			
			// aapt resource value: 0x7f0d0009
			public const int notification_action_icon_size = 2131558409;
			
			// aapt resource value: 0x7f0d000a
			public const int notification_action_text_size = 2131558410;
			
			// aapt resource value: 0x7f0d000b
			public const int notification_big_circle_margin = 2131558411;
			
			// aapt resource value: 0x7f0d0001
			public const int notification_content_margin_start = 2131558401;
			
			// aapt resource value: 0x7f0d000c
			public const int notification_large_icon_height = 2131558412;
			
			// aapt resource value: 0x7f0d000d
			public const int notification_large_icon_width = 2131558413;
			
			// aapt resource value: 0x7f0d0002
			public const int notification_main_column_padding_top = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public const int notification_media_narrow_margin = 2131558403;
			
			// aapt resource value: 0x7f0d000e
			public const int notification_right_icon_size = 2131558414;
			
			// aapt resource value: 0x7f0d0000
			public const int notification_right_side_padding_top = 2131558400;
			
			// aapt resource value: 0x7f0d000f
			public const int notification_small_icon_background_padding = 2131558415;
			
			// aapt resource value: 0x7f0d0010
			public const int notification_small_icon_size_as_large = 2131558416;
			
			// aapt resource value: 0x7f0d0011
			public const int notification_subtext_size = 2131558417;
			
			// aapt resource value: 0x7f0d0012
			public const int notification_top_pad = 2131558418;
			
			// aapt resource value: 0x7f0d0013
			public const int notification_top_pad_large_text = 2131558419;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070019
			public const int action0 = 2131165209;
			
			// aapt resource value: 0x7f070016
			public const int action_container = 2131165206;
			
			// aapt resource value: 0x7f07001d
			public const int action_divider = 2131165213;
			
			// aapt resource value: 0x7f070017
			public const int action_image = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int action_text = 2131165208;
			
			// aapt resource value: 0x7f070027
			public const int actions = 2131165223;
			
			// aapt resource value: 0x7f070010
			public const int async = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int blocking = 2131165201;
			
			// aapt resource value: 0x7f07001a
			public const int cancel_action = 2131165210;
			
			// aapt resource value: 0x7f070022
			public const int chronometer = 2131165218;
			
			// aapt resource value: 0x7f070029
			public const int end_padder = 2131165225;
			
			// aapt resource value: 0x7f070012
			public const int forever = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int ghost_view = 2131165184;
			
			// aapt resource value: 0x7f070024
			public const int icon = 2131165220;
			
			// aapt resource value: 0x7f070028
			public const int icon_group = 2131165224;
			
			// aapt resource value: 0x7f070023
			public const int info = 2131165219;
			
			// aapt resource value: 0x7f070013
			public const int italic = 2131165203;
			
			// aapt resource value: 0x7f07000a
			public const int line1 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int line3 = 2131165195;
			
			// aapt resource value: 0x7f07001c
			public const int media_actions = 2131165212;
			
			// aapt resource value: 0x7f070015
			public const int myButton = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int normal = 2131165204;
			
			// aapt resource value: 0x7f070026
			public const int notification_background = 2131165222;
			
			// aapt resource value: 0x7f07001f
			public const int notification_main_column = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int notification_main_column_container = 2131165214;
			
			// aapt resource value: 0x7f070001
			public const int parent_matrix = 2131165185;
			
			// aapt resource value: 0x7f070025
			public const int right_icon = 2131165221;
			
			// aapt resource value: 0x7f070020
			public const int right_side = 2131165216;
			
			// aapt resource value: 0x7f070002
			public const int save_image_matrix = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int save_non_transition_alpha = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int save_scale_type = 2131165188;
			
			// aapt resource value: 0x7f07001b
			public const int status_bar_latest_event_content = 2131165211;
			
			// aapt resource value: 0x7f07000c
			public const int tag_transition_group = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int text = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int text2 = 2131165198;
			
			// aapt resource value: 0x7f070021
			public const int time = 2131165217;
			
			// aapt resource value: 0x7f07000f
			public const int title = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int transition_current_scene = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int transition_layout_save = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int transition_position = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int transition_scene_layoutid_cache = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int transition_transform = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int cancel_button_image_alpha = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int status_bar_notification_info_maxnum = 2131361793;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_action = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_action_tombstone = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_media_action = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_media_cancel_action = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_big_media = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_big_media_custom = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_big_media_narrow = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_big_media_narrow_custom = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_custom_big = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_icon_group = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_template_lines_media = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_template_media = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_template_media_custom = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_template_part_chronometer = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int notification_template_part_time = 2130968591;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int wearable_app = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b0002
			public const int ApplicationName = 2131427330;
			
			// aapt resource value: 0x7f0b0001
			public const int Hello = 2131427329;
			
			// aapt resource value: 0x7f0b0004
			public const int app_name = 2131427332;
			
			// aapt resource value: 0x7f0b0003
			public const int hello = 2131427331;
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_overflow = 2131427328;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080005
			public const int TextAppearance_Compat_Notification = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Info = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Media = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Compat_Notification_Time = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int TextAppearance_Compat_Notification_Title = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int Widget_Compat_NotificationActionContainer = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int Widget_Compat_NotificationActionText = 2131230730;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int wearable_app_desc = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
